package handler

// 稳定错误码注册表（issue #149 P6）：respondError 第三参数量量的单一事实来源。
// 值与 P5 双写契约逐字一致；前端按 code 翻译（apiErrors.* 见 frontend/src/i18n/locales）。
const (
	// generic
	ErrCodeAvailabilityRequired = "availability_required"
	// auth
	ErrCodeCasdoorUserQueryFailed = "casdoor_user_query_failed"
	ErrCodeInvalidCredentials     = "invalid_credentials"
	ErrCodeInvalidInvite          = "invalid_invite"
	ErrCodeInvalidInviteId        = "invalid_invite_id"
	ErrCodeInvalidRefreshToken    = "invalid_refresh_token"
	ErrCodeInvalidRole            = "invalid_role"
	ErrCodeInvalidUserId          = "invalid_user_id"
	ErrCodeInvalidUserIdentity    = "invalid_user_identity"
	ErrCodeInviteCreationFailed   = "invite_creation_failed"
	ErrCodeInviteQueryFailed      = "invite_query_failed"
	ErrCodeInviteRevokeFailed     = "invite_revoke_failed"
	ErrCodeIssueTokenFailed       = "issue_token_failed"
	ErrCodeLoginFailed            = "login_failed"
	ErrCodeLoginLinkFailed        = "login_link_failed"
	ErrCodePasswordMismatch       = "password_mismatch"
	ErrCodePasswordResetFailed    = "password_reset_failed"
	ErrCodeRefreshTokenRequired   = "refresh_token_required"
	ErrCodeSelfOperationForbidden = "self_operation_forbidden"
	ErrCodeTokenNotFound          = "token_not_found"
	ErrCodeUnauthorized           = "unauthorized"
	ErrCodeUserNotFound           = "user_not_found"
	ErrCodeUserQueryFailed        = "user_query_failed"
	ErrCodeUserRoleUpdateFailed   = "user_role_update_failed"
	ErrCodeUserStatusUpdateFailed = "user_status_update_failed"
	// resource
	ErrCodeAgentDetailUnparseable  = "agent_detail_unparseable"
	ErrCodeAgentNotFound           = "agent_not_found"
	ErrCodeAgentQueryRequired      = "agent_query_required"
	ErrCodeAgentRuntimeNotFound    = "agent_runtime_not_found"
	ErrCodeAgentRuntimeUnavailable = "agent_runtime_unavailable"
	ErrCodeAgentUnavailable        = "agent_unavailable"
	ErrCodeAttachmentNotFound      = "attachment_not_found"
	ErrCodeInvalidAgentConfig      = "invalid_agent_config"
	ErrCodeInvalidToolFile         = "invalid_tool_file"
	ErrCodeKnowledgeError          = "knowledge_error"
	ErrCodeMcpNotFound             = "mcp_not_found"
	ErrCodeNotFound                = "not_found"
	ErrCodeProviderNotFound        = "provider_not_found"
	ErrCodeSceneNotFound           = "scene_not_found"
	ErrCodeSessionNotFound         = "session_not_found"
	// deploy
	ErrCodeDeployDeleteFailed        = "deploy_delete_failed"
	ErrCodeDeployFailed              = "deploy_failed"
	ErrCodeDeployStartFailed         = "deploy_start_failed"
	ErrCodeDeployStopFailed          = "deploy_stop_failed"
	ErrCodeDeploymentStatusUncertain = "deployment_status_uncertain"
	ErrCodeDeploymentUnhealthy       = "deployment_unhealthy"
	ErrCodeRuntimeProxyError         = "runtime_proxy_error"
	ErrCodeRuntimeUnreachable        = "runtime_unreachable"
	// upload
	ErrCodeAttachmentServiceUnavailable = "attachment_service_unavailable"
	ErrCodeMultipartRequired            = "multipart_required"
	ErrCodeTempFileUnavailable          = "temp_file_unavailable"
	ErrCodeUploadFailed                 = "upload_failed"
	ErrCodeUploadServiceError           = "upload_service_error"
	ErrCodeUploadServiceUnavailable     = "upload_service_unavailable"
	// 其他
	ErrCodeAigcFieldsRequired       = "aigc_fields_required"
	ErrCodeAlreadyInitialized       = "already_initialized"
	ErrCodeAuditQueryFailed         = "audit_query_failed"
	ErrCodeCasdoorOperationFailed   = "casdoor_operation_failed"
	ErrCodeConflict                 = "conflict"
	ErrCodeFieldRequired            = "field_required"
	ErrCodeIncompleteParameter      = "incomplete_parameter"
	ErrCodeInternalError            = "internal_error"
	ErrCodeInvalidId                = "invalid_id"
	ErrCodeInvalidPagination        = "invalid_pagination"
	ErrCodeInvalidParameter         = "invalid_parameter"
	ErrCodeInvalidSnapshotParameter = "invalid_snapshot_parameter"
	ErrCodeInvalidStatus            = "invalid_status"
	ErrCodeInvalidTimeRange         = "invalid_time_range"
	ErrCodeMultiragNotConfigured    = "multirag_not_configured"
	ErrCodeNameRequired             = "name_required"
	ErrCodeRateLimited              = "rate_limited"
	ErrCodeServiceUnavailable       = "service_unavailable"
	ErrCodeSessionIdRequired        = "session_id_required"
	ErrCodeSetupStatusFailed        = "setup_status_failed"
	ErrCodeStreamingUnsupported     = "streaming_unsupported"
	ErrCodeTypeQueryRequired        = "type_query_required"
	ErrCodeUnsupportedType          = "unsupported_type"
)
