import { useMemo } from 'react'
import { Empty, Select, Tag } from 'antd'
import { createStyles } from 'antd-style'
import type { Agent } from '@/api/agents'
import type { AgentRelation } from '@/api/agent-relations'
import type { RelationTypeTemplate } from '@/api/relation-types'
import { tokens as t } from '@/styles/tokens'

const useStyles=createStyles(({css})=>({shell:css`border:1px solid color-mix(in srgb,var(--foreground) 9%,transparent);border-radius:${t.radius}px;background:${t.surface};overflow:hidden;`,head:css`display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 16px;border-bottom:1px solid color-mix(in srgb,var(--foreground) 7%,transparent);`,copy:css`color:${t.textSecondary};font-size:${t.textSm};`,canvas:css`min-height:470px;overflow:auto;background:radial-gradient(circle at 1px 1px,color-mix(in srgb,var(--foreground) 9%,transparent) 1px,transparent 0);background-size:22px 22px;`,svg:css`display:block;min-width:760px;width:100%;height:470px;`,node:css`cursor:pointer;outline:none;&:focus-visible rect{stroke:${t.ink};stroke-width:3px}`,empty:css`padding:100px 20px;`}))

const label=(a:Agent)=>a.config.title?.zh??a.config.title?.en??a.name
export default function RelationTopology({agents,relations,types,focusId,onFocus,onEdge}:{agents:Agent[];relations:AgentRelation[];types:RelationTypeTemplate[];focusId?:number;onFocus:(id?:number)=>void;onEdge:(r:AgentRelation)=>void}){
 const {styles}=useStyles(); const visible=useMemo(()=>focusId?relations.filter(r=>r.sourceAgentId===focusId||r.targetAgentId===focusId):relations,[focusId,relations]); const ids=useMemo(()=>Array.from(new Set(visible.flatMap(r=>[r.sourceAgentId,r.targetAgentId]))),[visible]);
 const nodes=ids.map((id,i)=>{const angle=(Math.PI*2*i/Math.max(ids.length,1))-Math.PI/2;return{id,x:380+Math.cos(angle)*270,y:235+Math.sin(angle)*165,agent:agents.find(a=>a.id===id)}}); const pos=new Map(nodes.map(n=>[n.id,n]));
 return <div className={styles.shell}><div className={styles.head}><div className={styles.copy}><strong>通信拓扑</strong><br/>箭头表示消息与权限方向；点击 Agent 查看它的一跳关系。</div><Select allowClear placeholder="查看全部网络" value={focusId} style={{width:240}} onChange={onFocus} options={agents.map(a=>({value:a.id,label:`${label(a)} · ${a.name}`}))}/></div>{nodes.length===0?<div className={styles.empty}><Empty description="还没有可展示的关系"/></div>:<div className={styles.canvas}><svg className={styles.svg} viewBox="0 0 760 470" role="img" aria-label="Agent 关系拓扑"><defs><marker id="relation-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#64748b"/></marker></defs>{visible.map(r=>{const a=pos.get(r.sourceAgentId),b=pos.get(r.targetAgentId);if(!a||!b)return null;const type=types.find(x=>x.name===r.relationTypeTemplateName);return <g key={r.id} onClick={()=>{ onEdge(r); }} style={{cursor:'pointer'}}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={type?.lineColor??'#64748b'} strokeWidth="2" strokeDasharray={type?.lineStyle==='dashed'?'7 5':type?.lineStyle==='dotted'?'2 5':undefined} markerEnd="url(#relation-arrow)"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-7} textAnchor="middle" fill={t.textSecondary} fontSize="11">{type?.title??r.relationType}</text></g>})}{nodes.map(n=><g key={n.id} className={styles.node} tabIndex={0} onClick={()=>{ onFocus(n.id); }} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onFocus(n.id)}}><rect x={n.x-70} y={n.y-25} width="140" height="50" rx="12" fill={n.id===focusId?'var(--primary)':'var(--background)'} stroke={n.id===focusId?'var(--primary)':'#cbd5e1'} strokeWidth="1.5"/><text x={n.x} y={n.y-3} textAnchor="middle" fill={n.id===focusId?'white':t.text} fontSize="13" fontWeight="650">{(n.agent?label(n.agent):String(n.id)).slice(0,12)}</text><text x={n.x} y={n.y+14} textAnchor="middle" fill={n.id===focusId?'white':t.textMuted} fontSize="10">{n.agent?.name.slice(0,18)}</text></g>)}</svg></div>}<div style={{padding:'10px 16px'}}><Tag>{visible.length} 条有向边</Tag>{focusId&&<Tag>一跳视图</Tag>}</div></div>
}
