package agentrelation

import "errors"

var (
	ErrNotFound             = errors.New("Agent 关系不存在")
	ErrAlreadyExists        = errors.New("相同范围内的 Agent 关系已存在")
	ErrAgentNotFound        = errors.New("关系中的 Agent 不存在")
	ErrSelfRelation         = errors.New("不能创建 Agent 指向自身的关系")
	ErrInvalidScope         = errors.New("关系范围格式无效")
	ErrInvalidType          = errors.New("关系类型无效")
	ErrInvalidStance        = errors.New("关系立场无效")
	ErrInvalidAction        = errors.New("关系动作无效")
	ErrActionsRequired      = errors.New("请至少选择一个允许动作")
	ErrInvalidContext       = errors.New("上下文策略无效")
	ErrInvalidDelivery      = errors.New("投递策略无效")
	ErrConstraintTooLong    = errors.New("关系约束不能超过 2000 个字符")
	ErrBidirectionalType    = errors.New("该关系类型不能自动创建双向关系，请分别配置两个方向")
	ErrRouteNotFound        = errors.New("当前 Agent 到目标 Agent 没有已启用的关系")
	ErrActionNotAllowed     = errors.New("当前关系不允许执行该动作")
	ErrMessageNotFound      = errors.New("组织消息不存在")
	ErrMessageRequired      = errors.New("组织消息内容不能为空")
	ErrMessageTooLong       = errors.New("组织消息内容不能超过 16000 个字符")
	ErrNestedDispatch       = errors.New("当前 Agent 正在处理组织消息，不能在同一轮继续转发")
	ErrChainGuarded         = errors.New("消息链路已被预算守卫终止")
	ErrSyncDeadlock         = errors.New("同步消息会形成循环等待，请改用异步投递")
	ErrRunParticipantDenied = errors.New("目标 Agent 未参与本次运行，不能接收本次运行的消息")
	ErrInvalidEventType     = errors.New("关系事件类型无效")
	ErrInvalidSeverity      = errors.New("关系事件严重程度必须为 1、2 或 3")
	ErrInvalidVisibility    = errors.New("关系事件可见范围无效")
	ErrEventReasonRequired  = errors.New("请说明导致关系变化的具体事实")
	ErrEventReasonTooLong   = errors.New("关系事件说明不能超过 2000 个字符")
	ErrDynamicsReadOnly     = errors.New("旧动态关系已转为只读兼容，请使用能力包和运行状态")
)
