export interface IconOption {
  name: string
  label: string
  defaultColor: string
}

export const AGENT_ICON_OPTIONS: IconOption[] = [
  { name: 'ChatCircleDots', label: 'agentIcons.chat', defaultColor: '#3B82F6' },
  { name: 'ChartBar', label: 'agentIcons.chart', defaultColor: '#3B82F6' },
  { name: 'ShieldCheck', label: 'agentIcons.shield', defaultColor: '#8B5CF6' },
  { name: 'Crosshair', label: 'agentIcons.crosshair', defaultColor: '#10B981' },
  { name: 'UserCircle', label: 'agentIcons.userCircle', defaultColor: '#F97316' },
  { name: 'Terminal', label: 'agentIcons.terminal', defaultColor: '#6366F1' },
  { name: 'Robot', label: 'agentIcons.robot', defaultColor: '#06B6D4' },
  { name: 'Brain', label: 'agentIcons.brain', defaultColor: '#A855F7' },
  { name: 'Lightbulb', label: 'agentIcons.lightbulb', defaultColor: '#F59E0B' },
  { name: 'Cpu', label: 'agentIcons.cpu', defaultColor: '#64748B' },
  { name: 'MagicWand', label: 'agentIcons.magic', defaultColor: '#EC4899' },
  { name: 'Detective', label: 'agentIcons.detective', defaultColor: '#78716C' },
  { name: 'Compass', label: 'agentIcons.compass', defaultColor: '#0EA5E9' },
  { name: 'Rocket', label: 'agentIcons.rocket', defaultColor: '#F43F5E' },
  { name: 'GearSix', label: 'agentIcons.gear', defaultColor: '#6B7280' },
  { name: 'Code', label: 'agentIcons.code', defaultColor: '#22C55E' },
  { name: 'GraduationCap', label: 'agentIcons.education', defaultColor: '#7C3AED' },
  { name: 'GlobeHemisphereWest', label: 'agentIcons.globe', defaultColor: '#0284C7' },
  { name: 'PuzzlePiece', label: 'agentIcons.puzzle', defaultColor: '#D946EF' },
  { name: 'Eye', label: 'agentIcons.eye', defaultColor: '#14B8A6' },
  { name: 'Megaphone', label: 'agentIcons.megaphone', defaultColor: '#EA580C' },
  { name: 'Notebook', label: 'agentIcons.notebook', defaultColor: '#0891B2' },
  { name: 'FirstAidKit', label: 'agentIcons.firstAid', defaultColor: '#DC2626' },
  { name: 'Scales', label: 'agentIcons.scales', defaultColor: '#B45309' },
  { name: 'PresentationChart', label: 'agentIcons.presentation', defaultColor: '#4F46E5' },
  { name: 'ClipboardText', label: 'agentIcons.clipboard', defaultColor: '#65A30D' },
  { name: 'Headset', label: 'agentIcons.headset', defaultColor: '#2563EB' },
  { name: 'Wrench', label: 'agentIcons.wrench', defaultColor: '#9333EA' },
  { name: 'Lightning', label: 'agentIcons.lightning', defaultColor: '#EAB308' },
  { name: 'CurrencyDollar', label: 'agentIcons.finance', defaultColor: '#EF4444' },
]

export const PRESET_COLORS = [
  '#3B82F6',
  '#8B5CF6',
  '#10B981',
  '#F97316',
  '#EF4444',
  '#14B8A6',
  '#6366F1',
  '#6B7280',
  '#06B6D4',
  '#A855F7',
  '#F59E0B',
  '#EC4899',
  '#0EA5E9',
  '#F43F5E',
  '#22C55E',
  '#7C3AED',
  '#0284C7',
  '#D946EF',
  '#DC2626',
  '#4F46E5',
]

export const PRESET_BG_COLORS = [
  '#EBF0FF',
  '#F1EBFF',
  '#E6F9F1',
  '#FFF1E6',
  '#FFEBEB',
  '#E6FAF8',
  '#EBECFF',
  '#F0F1F2',
  '#E6F8FC',
  '#F5EBFF',
  '#FFF4E0',
  '#FDE8F3',
  '#E6F5FD',
  '#FEE8EC',
  '#E8FCE8',
  '#EDE8FF',
  '#E4F2FA',
  '#FAE8FC',
  '#D9E4FF',
  '#E3D6FF',
  '#CDF4E3',
  '#FFE4CC',
  '#FFD6D6',
  '#CCF5F0',
]
