export interface IconOption {
  name: string
  label: string
  defaultColor: string
}

export const AGENT_ICON_OPTIONS: IconOption[] = [
  { name: 'ChatCircleDots', label: '通用对话', defaultColor: '#3B82F6' },
  { name: 'ChartBar', label: '数据分析', defaultColor: '#3B82F6' },
  { name: 'ShieldCheck', label: '安全合规', defaultColor: '#8B5CF6' },
  { name: 'Crosshair', label: '精准定位', defaultColor: '#10B981' },
  { name: 'UserCircle', label: '用户管理', defaultColor: '#F97316' },
  { name: 'Terminal', label: '终端运维', defaultColor: '#6366F1' },
  { name: 'Robot', label: '智能助手', defaultColor: '#06B6D4' },
  { name: 'Brain', label: 'AI 智能', defaultColor: '#A855F7' },
  { name: 'Lightbulb', label: '创意灵感', defaultColor: '#F59E0B' },
  { name: 'Cpu', label: '计算处理', defaultColor: '#64748B' },
  { name: 'MagicWand', label: 'AI 生成', defaultColor: '#EC4899' },
  { name: 'Detective', label: '调查分析', defaultColor: '#78716C' },
  { name: 'Compass', label: '导航指引', defaultColor: '#0EA5E9' },
  { name: 'Rocket', label: '高速执行', defaultColor: '#F43F5E' },
  { name: 'GearSix', label: '工程配置', defaultColor: '#6B7280' },
  { name: 'Code', label: '编程开发', defaultColor: '#22C55E' },
  { name: 'GraduationCap', label: '教育学习', defaultColor: '#7C3AED' },
  { name: 'GlobeHemisphereWest', label: '全球化', defaultColor: '#0284C7' },
  { name: 'PuzzlePiece', label: '集成连接', defaultColor: '#D946EF' },
  { name: 'Eye', label: '监控观测', defaultColor: '#14B8A6' },
  { name: 'Megaphone', label: '营销推广', defaultColor: '#EA580C' },
  { name: 'Notebook', label: '知识管理', defaultColor: '#0891B2' },
  { name: 'FirstAidKit', label: '健康医疗', defaultColor: '#DC2626' },
  { name: 'Scales', label: '法务平衡', defaultColor: '#B45309' },
  { name: 'PresentationChart', label: '商业展示', defaultColor: '#4F46E5' },
  { name: 'ClipboardText', label: '任务管理', defaultColor: '#65A30D' },
  { name: 'Headset', label: '客户服务', defaultColor: '#2563EB' },
  { name: 'Wrench', label: '维修工具', defaultColor: '#9333EA' },
  { name: 'Lightning', label: '快速响应', defaultColor: '#EAB308' },
  { name: 'CurrencyDollar', label: '财务金融', defaultColor: '#EF4444' },
]

export const PRESET_COLORS = [
  '#3B82F6',
  '#8B5CF6',
  '#10B981',
  '#F97316',
  '#EF4444',
  '#14B8A6',
  '#6366F1',
  '#6B7280',
  '#06B6D4',
  '#A855F7',
  '#F59E0B',
  '#EC4899',
  '#0EA5E9',
  '#F43F5E',
  '#22C55E',
  '#7C3AED',
  '#0284C7',
  '#D946EF',
  '#DC2626',
  '#4F46E5',
]

export const PRESET_BG_COLORS = [
  '#EBF0FF',
  '#F1EBFF',
  '#E6F9F1',
  '#FFF1E6',
  '#FFEBEB',
  '#E6FAF8',
  '#EBECFF',
  '#F0F1F2',
  '#E6F8FC',
  '#F5EBFF',
  '#FFF4E0',
  '#FDE8F3',
  '#E6F5FD',
  '#FEE8EC',
  '#E8FCE8',
  '#EDE8FF',
  '#E4F2FA',
  '#FAE8FC',
  '#D9E4FF',
  '#E3D6FF',
  '#CDF4E3',
  '#FFE4CC',
  '#FFD6D6',
  '#CCF5F0',
]
